### ISSUE TITLE
Root dir already exists (Fail Fast)

### ISSUE THREAD

**Issue by wintron04** [isbm/berrymill#36]
Berrymill should not load appliance, read config and perform various checks before it calls kiwi, just so that kiwi fails with this error.

Berrymill shall check for a existing root directory itself and propose the **--clean** flag to the user

Fail fast!

**Comment by isbm** [comment]
Probably also have a map of those CPUs and pre-choose one, if 100% sure?

**Comment by osab270844** [comment]
In addition, --clean argument position shouldn't matter, in other words, --clean at the end of the cmdline shouldn't make berrymill fails.
